config/routes.rb
Rails.application.routes.draw do
  root    'posts#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    collection do
      get ":id/likes" => "users#likes", as: :likes
      get ":id/comments" => "users#comments", as: :comments
    end
  end
  devise_scope :user do
    get 'profile/:id/' => 'users/registrations#profile', as: 'profile'
    get 'profile/:id/following', to: 'users/registrations#following', as: 'following'
    get 'profile/:id/followers', to: 'users/registrations#followers', as: 'followers'
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/module/_header_small_nav.html.erb
<div class="header_small_nav">
  <i class="fas fa-bars">
    <ul class = "user__info">
      <li>
        <i class="fas fa-newspaper"></i><%= link_to '最新の投稿一覧', root_path %>
      <% if user_signed_in? %>
        <%# <li>
          <i class="fas fa-address-book"></i><%= link_to 'フォロワーの投稿一覧', '#' %>
        <%# </li> %>
        <li>
          <i class="fas fa-comments"></i><%= link_to 'コメントした投稿一覧', comments_users_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-heart"></i><%= link_to 'いいねした投稿一覧', likes_users_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-user"></i><%= link_to 'マイページ', user_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-cog"></i><%= link_to 'ユーザー情報の編集', edit_user_registration_path %>
        </li>
        <li>
          <i class="fas fa-door-closed"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <i class="fas fa-door-open"></i><%= link_to "ログイン", user_session_path %>
        </li>
        <li>
          <i class="fas fa-user-plus"></i><%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </li>
      <% end %>
    </ul>
  </i>
</div>

app/views/module/_sidebar.html.erb
<div class="sidebar contents fixed">
  <div class="contents_list sidebar_item">
    <div class="btn">
      <a class="" href="/posts/new">
      <i class="fas fa-pen"></i>投稿する</a>
    </div>
    <div class="section_title">
      <i class="fas fa-bars"></i>MENU</div>
    <ul>
      <li>
        <i class="fas fa-newspaper"></i><%= link_to '最新の投稿一覧', root_path %>
      <% if user_signed_in? %>
        <%# <li> %>
          <%# <i class="fas fa-address-book"></i><%= link_to 'フォロワーの投稿一覧', '#' %>
        <%# </li> %>
        <li>
          <i class="fas fa-comments"></i><%= link_to 'コメントした投稿一覧', comments_users_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-heart"></i><%= link_to 'いいねした投稿一覧', likes_users_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-user"></i><%= link_to 'マイページ', user_path(current_user.id) %>
        </li>
        <li>
          <i class="fas fa-cog"></i><%= link_to 'ユーザー情報の編集', edit_user_registration_path %>
        </li>
        <li>
          <i class="fas fa-door-closed"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <i class="fas fa-door-open"></i><%= link_to "ログイン", user_session_path %>
        </li>
        <li>
          <i class="fas fa-user-plus"></i><%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </li>
      <% end %>
    </ul>
    <%# <div class="section_title">
      <i class="fas fa-calendar-alt"></i>今月の学習時間TOP3</div>
    <ul>
      <li class="ranking">
        <i class="fas fa-crown gold"></i>ナルトさん：6000min(100hour)</li>
      <li class="ranking">
        <i class="fas fa-crown silver"></i>サスケさん：4500min(75hour)</li>
      <li class="ranking">
        <i class="fas fa-crown bronze"></i>サクラさん：3000min(50hour)</li>
    </ul>
    <div class="section_title">
      <i class="fas fa-calendar-week"></i>今週の学習時間TOP3</div>
    <ul>
      <li class="ranking">
        <i class="fas fa-crown gold"></i>きり丸さん：600min(10hour)</li>
      <li class="ranking">
        <i class="fas fa-crown silver"></i>しんべえさん：450min(7.5hour)</li>
      <li class="ranking">
        <i class="fas fa-crown bronze"></i>乱太郎さん：300min(5hour)</li>
    </ul> %>
  </div>
</div>