config/routes.rb
Rails.application.routes.draw do
  root    'posts#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    collection do
      get ":id/likes" => "users#likes", as: :likes
      get ":id/comments" => "users#comments", as: :comments
    end
  end
  devise_scope :user do
    get 'profile/:id/' => 'users/registrations#profile', as: 'profile'
    get 'profile/:id/following', to: 'users/registrations#following', as: 'following'
    get 'profile/:id/followers', to: 'users/registrations#followers', as: 'followers'
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  counter_culture :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def create
    Like.create(post_id: params[:post_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
  end

  def destroy
    unlike = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    unlike.destroy if unlike.user_id == current_user.id
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
  end

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end

  def likes_params
    params.permit(:post_id, :user_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= post.id %>">
  <% if user_signed_in? %>
    <% if current_user.likes.find_by(post_id: post.id) %>
      <%= link_to post_like_path(post.id), method: :delete, remote: true do %>
        <div><i class="fas fa-heart liked"></i><%= post.likes_count %></div>
      <% end %>
    <% else %>
      <%= link_to post_likes_path(post.id), method: :post, remote: true do %>
        <div><i class="far fa-heart"></i><%= post.likes_count %></div>
      <% end %>
    <% end %>
  <% else %>
    <div><i class="far fa-heart"></i><%= post.likes_count %></div>
  <% end %>
</div>