config/routes.rb
Rails.application.routes.draw do
  root    'posts#index'
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    collection do
      get ":id/likes" => "users#likes", as: :likes
      get ":id/comments" => "users#comments", as: :comments
    end
  end
  devise_scope :user do
    get 'profile/:id/' => 'users/registrations#profile', as: 'profile'
    get 'profile/:id/following', to: 'users/registrations#following', as: 'following'
    get 'profile/:id/followers', to: 'users/registrations#followers', as: 'followers'
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :text
    validates :date
    validates :study_time
  end
  validates :study_time, format: { with: /\A[0-9]+\z/ }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_post, except: [:index, :new, :create]
  helper_method :monthly_ranking

  def index
    @posts = Post.includes(:user).page(params[:page]).per(5).order("created_at DESC").limit(50)
  end

  def new
  end

  def create
    @new_post = Post.new(date: post_params[:date], study_time: post_params[:study_time], text: post_params[:text], user_id: current_user.id)
    unless @new_post.save
      flash.now[:alert] = '必須項目が入力されていません。'
      render :new
    end
  end

  def destroy
    @post.destroy if @post.user_id == current_user.id
  end

  def edit
    if @post.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    if @post.user_id == current_user.id
      unless @post.update(post_params)
        flash.now[:alert] = '必須項目が入力されていません。'
        render :edit
      end
    end

  end

  def show
    @comments = @post.comments.includes(:user)
  end

  # def monthly_ranking
  #   binding.pry
  #   @monthly_ranking = User.find(Post.group(:user_id).order('sum(:study_time) desc').limit(3))
  # end

  private
    def post_params
      params.permit(:date, :study_time, :text)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

    def set_post
      @post = Post.find(params[:id])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="content_post">
  <%= link_to('',post_path(post.id),class:"post-link") %>
  <div class="post_container">
    <div class="user_image">
      <%= link_to user_path(post.user.id) do%>
        <% if post.user.image? %>
          <%= image_tag post.user.image.url %>
        <% else %>
          <%= image_tag "user_default.png" %>
        <% end %>
      <% end %>
    </div>
    <div class="content-right">
      <div class="post_header">
        <%= link_to(post.user.nickname, user_path(post.user.id),) %>
        <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
      <div class="content_desc">
        <div><i class="fas fa-calendar"></i><%= post.date %></div>
        <div><i class="fas fa-clock"></i><%= post.study_time %>分</div>
        <div class="content_txt"><p><%= simple_format(post.text) %></p></div>
      </div>
      <div class="content_footer">
        <div class="icon_list">
          <div><i class="far fa-comment"></i><%= post.comments_count %></div>
          <div><i class="far fa-heart"></i><%= post.likes_count %></div>
        </div>
        <% if user_signed_in? && current_user.id == post.user_id %>
          <div class="more">
            <i class="fas fa-ellipsis-h"></i>
            <ul class="more_list">
              <li>
                <%= link_to '削除', "/posts/#{post.id}", method: :delete %>
              </li>
              <li>
                <%= link_to '編集', "/posts/#{post.id}/edit", method: :get %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/users/<%= current_user.id %>">マイページへ戻る</a>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag("/posts/#{@post.id}", method: :patch ) do %>
      <h3>
        編集する
      </h3>
      <div class="notifications">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key)%>
        <% end %>
      </div>
      <label for="input-date">学習日</label>
      <input placeholder="日付を入力" type="date" id="input-date" name="date" value="<%= @post.date %>" autofocus="true">
      <label for="input-study-time">学習時間<span>(半角数字)</span></label>
      <input placeholder="勉強時間を入力(半角数字)" type="integer" id="input-study-time" name="study_time" value="<%= @post.study_time %>" autofocus="true">
      <label for="input-text">学習内容</label>
      <textarea cols="30" id="input-text" name="text" placeholder="text" rows="10"><%= @post.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="contents" >
  <p>最新の投稿一覧</p>
  <div class="contents_list">
    <% @posts.each do |post| %>
      <%= render partial: "post", locals: { post: post } %>
    <% end %>
  </div>
  <%= paginate(@posts) %>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/posts', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <div class="notifications">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key)%>
        <% end %>
      </div>
      <label for="input-date">学習日</label>
      <input placeholder="日付を入力" type="date" id="input-date" name="date">
      <label for="input-study-time">学習時間<span>(半角数字)</span></label>
      <input placeholder="勉強時間を分単位で入力(半角数字)" type="integer" id="input-study-time" name="study_time">
      <label for="input-text">学習内容</label>
      <textarea cols="30" id="input-text" name="text" placeholder="text" rows="10"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class ="contents">
  <div class="contents_list">
    <div class="content_post post-show">
      <div class="post_container">
        <div class="user_image">
          <%= link_to user_path(@post.user.id) do%>
            <% if @post.user.image? %>
              <%= image_tag @post.user.image.url %>
            <% else %>
              <%= image_tag "user_default.png" %>
            <% end %>
          <% end %>
        </div>
        <div class="content-right">
          <div class="post_header">
            <%= link_to @post.user.nickname, user_path(@post.user.id) %>
            <p><%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          </div>
          <div class="content_desc">
            <div><i class="fas fa-calendar"></i><%= @post.date %></div>
            <div><i class="fas fa-clock"></i><%= @post.study_time %>分</div>
            <div class="content_txt"><%= simple_format(@post.text) %></div>
          </div>
          <div class="content_footer">
            <div class="icon_list">
              <div><i class="far fa-comment"></i><%= @post.comments_count %></div>
              <%= render partial: "likes/like", locals: { post: @post } %>
            </div>
            <div class="more">
              <i class="fas fa-ellipsis-h"></i>
              <ul class="more_list">
                <% if user_signed_in? && current_user.id == @post.user_id %>
                  <li>
                    <%= link_to '削除', "/posts/#{@post.id}", method: :delete %>
                  </li>
                  <li>
                    <%= link_to '編集', "/posts/#{@post.id}/edit", method: :get %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/posts/#{@post.id}/comments",  method: :post,  id: "new_comment" ) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2" class="textbox"></textarea>
        <input type="submit" value="SEND" class="form__submit">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>